netty:
  websocket:
    port: 7789
    ip: 127.0.0.1
sever:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:com.web_programming.data_collecting_server.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
